spring:
  data:
    mongodb:
      host: 127.0.0.1 #指定MongoDB服务地址
      port: 27017 #指定端口，默认就为27017
      database: article #指定使用的数据库
      authentication-database: admin # 登录认证的逻辑库名
      username: admin #用户名
      password: abc123456 #密码
